version: '3'
services:
  elasticsearch:
    image: nshou/elasticsearch-kibana
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
      - 5601:5601
    restart: on-failure  
    networks:
      - elastic
  jaeger:
    image: jaegertracing/all-in-one:1.21
    container_name: jaeger
    command: ["--es.server-urls=http://elasticsearch:9200"]
    environment:
      - node.name=jaeger
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_TAGS_AS_FIELDS_ALL=true
      - LOG_LEVEL=debug
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411
    restart: on-failure  
    depends_on:
      - elasticsearch  
    networks:
      - elastic
  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      - node.name=grafana
    ports:
      - 3000:3000
    restart: on-failure  
    networks:
      - elastic
  otel-collector:
    image: otel/opentelemetry-collector
    container_name: otel-collector
    command: ["--config=/etc/otel-local-config.yaml","--log-level=DEBUG"]
    volumes:
      - ./otel-local-config.yaml:/etc/otel-local-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"        # OTLP gRPC receiver
      - "55670:55679" # zpages extension
      - "8081:8081"
      - "55680:55680"
    depends_on:
      - jaeger
    networks:
      - elastic
  otel-collector2:
    image: otel/opentelemetry-collector
    container_name: otel-collector2
    command: ["--config=/etc/otel-local-config2.yaml","--log-level=DEBUG"]
    volumes:
      - ./otel-local-config2.yaml:/etc/otel-local-config2.yaml
    ports:
      - "9092:9092"
    depends_on:
      - otel-collector
    networks:
      - elastic

networks:
  elastic:
    driver: bridge